#!/bin/bash
#For a given month, outputs each submitting lab with number of samples and proportion of total samples for that month
#make sure to run this script in a folder with one tsv file of DC sequences named gisaid*.tsv (downloaded from GISAID; download --> input for the Augur pipeline)
#extract a particular month from the file
grep "2021-02" gisaid*.tsv > input_by_month.tsv
#print the month
printf "SARS-CoV-2 samples from DC submitted 2021-02"
#print the number of samples from that month for each facility
printf "Number of samples by submitting laboratory:\n"
awk -F"\t" '{print $21}' input_by_month.tsv | sort | uniq -c | sort -nr | awk '{s+=$1;lines=lines"\n"$0} END {printf "%d Total",s;print lines}' | awk '!max{max=$1}{s=$1/max*100;c=$1;$1="";printf "%30s %10d %7.2f%%\n",$0,c,s;}'
