#!/usr/bin/env bash
#Combination of filter_VOC.sh and compare_VOC_lists.sh
#Make sure you have a file of all DC SARS-CoV-2 sequences from GISAID called *metadata.tsv (download as Input for Augur Pipeline) and a file of your previous sequences, called all_VOC_*.tsv (with strain names in column 3)
#Output is new_VOCs.tsv, which contains all VOCs that are in the newly-downloaded file but not in the old file
#There is a blank column for adding LIMS IDs

#Filter a tsv file to show only variants of concern
awk -F"\t" '$19 ~ "B.1.1.7" || $19 ~ "Q." || $19 ~ "B.1.351" || $19 ~ "P.1" || $19 ~ "B.1.617.2" || $19 ~ "AY." {print $27, "\t", "\t", $1, "\t", $5, "\t", $19, "\t", $21, "\t", $22}' *metadata.tsv > VOCs.tsv
awk -F"\t" '{print $3}' VOCs.tsv > VOC_names.tsv
awk -F"\t" '{print $3}' all_VOC_*.tsv > masterlist_names.tsv
comm -2 -3 <(sort VOC_names.tsv) <(sort masterlist_names.tsv) > difflist.tsv
rm VOC_names.tsv
rm masterlist_names.tsv
awk -F"\t" 'FNR==NR{a[$1]=$1; next}; $3 in a {print $0;}' difflist.tsv VOCs.tsv > new_VOCs.tsv
