#!/usr/bin/env bash
#Make sure you have a file of all DC SARS-CoV-2 sequences from GISAID called *metadata.tsv (download as Input for Augur Pipeline) and a file of your previous sequences, called all_VOC_*.tsv (with strain names in column 3)
#Output is new_VOCs.tsv, which contains all VOCs that are in the newly-downloaded file but not in the old file
#There is a blank column for adding LIMS IDs

#Filter a tsv file to show only variants of concern
awk -F"\t" '$19 ~ "B.1.1.7" || $19 ~ "Q." || $19 ~ "B.1.351" || $19 ~ "P.1" || $19 ~ "B.1.617.2" || $19 ~ "AY." {print $27, "\t", "\t", $1, "\t", $5, "\t", $19, "\t", $21, "\t", $22}' *metadata.tsv > VOCs.tsv
#Transfer the strain names from the new file and the master list to new files
awk -F"\t" '{print $3}' VOCs.tsv > VOC_names.tsv
awk -F"\t" '{print $3}' all_VOC_*.tsv > masterlist_names.tsv
#Take out spaces from before or after each strain name
cat VOC_names.tsv | sed 's/^[ \t]*//;s/[ \t]*$//' > newlist.tsv
cat masterlist_names.tsv | sed 's/^[ \t]*//;s/[ \t]*$//' > oldlist.tsv
#Sort the lists, because this will be needed for the comm command
sort newlist.tsv > list1.tsv
sort oldlist.tsv > list2.tsv
#Make a list of the strain names in the new file that are not in the master list; put this in difflist.tsv
comm -2 -3 list1.tsv list2.tsv > difflist.tsv
#Get rid of unnecessary files
rm VOC_names.tsv
rm masterlist_names.tsv
rm newlist.tsv
rm oldlist.tsv
rm list1.tsv 
rm list2.tsv
