#!/usr/bin/env bash
#For the Nextclade CLI SARS-CoV-2 pipeline (https://github.com/nextstrain/ncov), generate DC PHL-only tsv and fasta files from all-DC tsv and fasta files (from files downloaded from gisaid.org as "input for Augur pipeline")
#This script will create a new, filtered file for every tsv and fasta file in the working directory
#The new files will start with the prefix "PHLonly_"

#filter tsv file
for tsv_file in *.tsv
do
	awk -F"\t" '$1 ~ "DC-DFS-PHL" {print $0}' ${tsv_file} > "PHLonly_${tsv_file}"
done

#filter fasta file
for fasta_file in *.fasta
do
	awk '/^>/{if($0 ~ /DC-DFS-PHL/){f=1} else {f=0;}} f==1{print;}' ${fasta_file}  > "PHLonly_${fasta_file}"
done 
