#!/usr/bin/env bash
#For the Nextclade CLI SARS-CoV-2 pipeline (https://github.com/nextstrain/ncov), generate DC PHL-only tsv and fasta files from all-DC tsv and fasta files (from files downloaded from gisaid.org as "input for Augur pipeline")
#This script will create a new, filtered file for every tsv and fasta file in the working directory
#The new files will start with the prefix "PHLonly_"

#filter tsv file
for tsv_file in *.tsv
do
	printf "strain\tvirus\tgisaid_epi_isl\tdate\tregion\tcountry\tdivision\tlocation\tregion_exposure\tcountry_exposure\tdivision_exposure\tsegment\tlength\thost\tage\tsex\tpangolin_lineage\tGISAID_clade\toriginating_lab\tsubmitting_lab\tauthors\turl\ttitle\tpaper_url\tdate_submitted\tpurpose_of_sequencing\n" > "PHLonly_${tsv_file}"
	awk -F"\t" '$1 ~ "DC-DFS-PHL" {print $0}' ${tsv_file} >> "PHLonly_${tsv_file}"
done

#filter fasta file
for fasta_file in *.fasta
do
	awk '/^>/{if($0 ~ /DC-DFS-PHL/){f=1} else {f=0;}} f==1{print;}' ${fasta_file}  > "PHLonly_${fasta_file}"
done 
