#!/usr/bin/env bash
#Look up LIMS IDs, based on strain name. 
#LIMS IDs must be in a txt file called LIMS.txt
#Reference table must be called REF.txt
#output is called output.txt and is the full line from the reference table

grep -Ff LIMS.txt REF.txt > output.txt
