#!/usr/bin/env bash
#remove leading and trailing white space from a list
#input is *.tsv, or change code to reflect appropriate file

#trim function from stack overflow
trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   
    printf '%s\n' "$var"
}

#read file line by line, invoke trim function
while read -r line;
do
	trim $line >> output.tsv
done < *.tsv
