#!/usr/bin/env bash
#Run this script in a folder with one tsv file of DC sequences named gisaid*.tsv (downloaded from GISAID; download --> Sequencing Technology Metadata)
#To see sub-lineage breakdowns, open the files DCtotal.tsv and PHLonly.tsv and sort by lineage name.

#Print the total number of sequences for DC and DC-DFS-PHL
printf "\nTotals\n"
(printf '%s:\t\t' "Total SARS-CoV-2 GISAID submissions in DC" ; grep -c "hCoV-19" gisaid*.tsv)
(printf '%s:\t' "Total SARS-CoV-2 GISAID submissions by DC-DFS-PHL" ; grep -c "DC-DFS-PHL" gisaid*.tsv)
printf "\n\n"

#Make a spreadsheet of the number/percentage of variants for all labs in DC
#printf "\nNumber and percentage of variants in DC:\nLineage:\tNum:\tPerc:\n"
awk -F"\t" '{print $13}' gisaid*.tsv | sort | uniq -c | sort -nr | awk '{s+=$1;lines=lines"\n"$0} END {printf "%d Total",s;print lines "\t"}' | awk '!max{max=$1}{s=$1/max*100;c=$1;$1="";printf "%-10s \t %10d \t %7.2f%%\n",$0,c,s;}' > "DCtotal.tsv"

#Make a spreadsheet of the number/percentage of variants for DC-DFS-PHL
#printf "\nNumber and percentage of variants for PHL:\nLineage:\tNum:\tPerc:\n"
awk -F"\t" '{if ($1 ~ "DFS-PHL") print $13;}' gisaid*.tsv | sort | uniq -c | sort -nr | awk '{s+=$1;lines=lines"\n"$0} END {printf "%d Total",s;print lines "\t"}' | awk '!max{max=$1}{s=$1/max*100;c=$1;$1="";printf "%-10s \t %10d \t %7.2f%%\n",$0,c,s;}' > "PHLonly.tsv"

#Search the spreadsheets and report out the variant counts
printf "\n\n"
echo "from DC (total)"
printf "\n"
#Delta
awk -F"\t" '$1 ~ "B.1.617.2" || $1 ~ /AY\..../ {sum+=$2} END {printf "Delta (B.1.617.2, AY.#):" "\t" sum "\n"}' DCtotal.tsv
#Omicron 
awk -F"\t" '$1 ~ "B.1.1.529" || $1 ~ /BA\..../ {sum+=$2} END {printf "Omicron (B.1.1.529, BA.#):" "\t" sum "\n"}' DCtotal.tsv
#Alpha
awk -F"\t" '$1 ~ "B.1.1.7" || $1 ~ /Q\..../ {sum+=$2} END {printf "Alpha (B.1.1.7, Q.#):" "\t\t" sum "\n"}' DCtotal.tsv
#Gamma
awk -F"\t" '$1 ~ "P.1" || $1 ~ /P\.1\..../ {sum+=$2} END {printf "Gamma (P.1, P.1.#):" "\t\t" sum "\n"}' DCtotal.tsv
#Zeta
awk -F"\t" '$1 ~ "P.2" || $1 ~ /P\.2\..../ {sum+=$2} END {printf "Zeta (P.2, P.2.#):" "\t\t" sum "\n"}' DCtotal.tsv
#Beta
awk -F"\t" '$1 ~ "B.1.351" || $1 ~ /B\.1\.351\..../ {sum+=$2} END {printf "Beta (B.1.351, B.1.351.#):" "\t" sum "\n"}' DCtotal.tsv
#Kappa
awk -F"\t" '$1 ~ "B.1.617.1" {sum+=$2} END {printf "Kappa (B.1.617.1):" "\t\t" sum "\n"}' DCtotal.tsv
#B.1.617.3
awk -F"\t" '$1 ~ "B.1.617.3" {sum+=$2} END {printf "[None] (B.1.617.3):" "\t\t" sum "\n"}' DCtotal.tsv
#Epsilon1
awk -F"\t" '$1 ~ "B.1.427" || $1 ~ /B\.1\.427\..../ {sum+=$2} END {printf "Epsilon (B.1.427, B.1.427.#):" "\t" sum "\n"}' DCtotal.tsv
#Epsilon2
awk -F"\t" '$1 ~ "B.1.429" || $1 ~ /B\.1\.429\..../ {sum+=$2} END {printf "Epsilon (B.1.429, B.1.429.#):" "\t" sum "\n"}' DCtotal.tsv
#Eta
awk -F"\t" '$1 ~ "B.1.525" || $1 ~ /B\.1\.525\..../ {sum+=$2} END {printf "Eta (B.1.525, B.1.525.#):" "\t" sum "\n"}' DCtotal.tsv
#Iota
awk -F"\t" '$1 ~ "B.1.526" || $1 ~ /B\.1\.526\..../ {sum+=$2} END {printf "Iota (B.1.526, B.1.526.#):" "\t" sum "\n"}' DCtotal.tsv
#Mu
awk -F"\t" '$1 ~ "B.1.621" || $1 ~ /B\.1\.621\..../ {sum+=$2} END {printf "Mu (B.1.621, B.1.621.#):" "\t" sum "\n"}' DCtotal.tsv
#Lambda
awk -F"\t" '$1 ~ "C.37" || $1 ~ /C\.37\..../ {sum+=$2} END {printf "Lambda (C.37, C.37.#):" "\t" sum "\n"}' DCtotal.tsv

printf "\n\n"
echo "from DC-DFS-PHL"
printf "\n"

#Delta
awk -F"\t" '$1 ~ "B.1.617.2" || $1 ~ /AY\..../ {sum+=$2} END {printf "Delta (B.1.617.2, AY.#):" "\t" sum "\n"}' PHLonly.tsv
#Omicron 
awk -F"\t" '$1 ~ "B.1.1.529" || $1 ~ /BA\..../ {sum+=$2} END {printf "Omicron (B.1.1.529, BA.#):" "\t" sum "\n"}' PHLonly.tsv
#Alpha
awk -F"\t" '$1 ~ "B.1.1.7" || $1 ~ /Q\..../ {sum+=$2} END {printf "Alpha (B.1.1.7, Q.#):" "\t\t" sum "\n"}' PHLonly.tsv
#Gamma
awk -F"\t" '$1 ~ "P.1" || $1 ~ /P\.1\..../ {sum+=$2} END {printf "Gamma (P.1, P.1.#):" "\t\t" sum "\n"}' PHLonly.tsv
#Zeta
awk -F"\t" '$1 ~ "P.2" || $1 ~ /P\.2\..../ {sum+=$2} END {printf "Zeta (P.2, P.2.#):" "\t\t" sum "\n"}' PHLonly.tsv
#Beta
awk -F"\t" '$1 ~ "B.1.351" || $1 ~ /B\.1\.351\..../ {sum+=$2} END {printf "Beta (B.1.351, B.1.351.#):" "\t" sum "\n"}' PHLonly.tsv
#Kappa
awk -F"\t" '$1 ~ "B.1.617.1" {sum+=$2} END {printf "Kappa (B.1.617.1):" "\t\t" sum "\n"}' PHLonly.tsv
#B.1.617.3
awk -F"\t" '$1 ~ "B.1.617.3" {sum+=$2} END {printf "[None] (B.1.617.3):" "\t\t" sum "\n"}' PHLonly.tsv
#Epsilon1
awk -F"\t" '$1 ~ "B.1.427" || $1 ~ /B\.1\.427\..../ {sum+=$2} END {printf "Epsilon (B.1.427, B.1.427.#):" "\t" sum "\n"}' PHLonly.tsv
#Epsilon2
awk -F"\t" '$1 ~ "B.1.429" || $1 ~ /B\.1\.429\..../ {sum+=$2} END {printf "Epsilon (B.1.429, B.1.429.#):" "\t" sum "\n"}' PHLonly.tsv
#Eta
awk -F"\t" '$1 ~ "B.1.525" || $1 ~ /B\.1\.525\..../ {sum+=$2} END {printf "Eta (B.1.525, B.1.525.#):" "\t" sum "\n"}' PHLonly.tsv
#Iota
awk -F"\t" '$1 ~ "B.1.526" || $1 ~ /B\.1\.526\..../ {sum+=$2} END {printf "Iota (B.1.526, B.1.526.#):" "\t" sum "\n"}' PHLonly.tsv
#Mu
awk -F"\t" '$1 ~ "B.1.621" || $1 ~ /B\.1\.621\..../ {sum+=$2} END {printf "Mu (B.1.621, B.1.621.#):" "\t" sum "\n"}' PHLonly.tsv
#Lambda
awk -F"\t" '$1 ~ "C.37" || $1 ~ /C\.37\..../ {sum+=$2} END {printf "Lambda (C.37, C.37.#):" "\t" sum "\n"}' PHLonly.tsv
