#!/usr/bin/env bash
#Run this script in a folder with one tsv file of DC sequences (downloaded from GISAID; download --> Sequencing Technology Metadata; rename files so they start with "gisaid" and end with ".tsv")

#Make specific files to be used later
awk -F"\t" '$1 ~ "DC-DFS-PHL"' gisaid*.tsv > PHL.tsv
awk -F"\t" '$1 ~ "hCoV-19"' gisaid*.tsv > DC.tsv

#Print the number of sequences for DC and DC-DFS-PHL
printf "# sequences from DC: "
grep -c "hCoV-19" DC.tsv
printf "# sequences from DFS-PHL: "
grep -c "DC-DFS-PHL" PHL.tsv

#Print the number of Omicron sequences (based on clade GRA)
printf "# Omicron sequences from DC (# clade GRA): "
grep -c "GRA" DC.tsv
printf "# Omicron sequences from DFS-PHL (# clade GRA): "
grep -c "GRA" PHL.tsv

#Make a spreadsheet of the number/percentage of variants for all labs for DC and DC-DFS-PHL
awk -F"\t" '{print $14}' DC.tsv | sed -r 's/.[(].*//g' | sort | uniq -c | awk '{s+=$1;lines=lines"\n"$0} END {printf "%d Total",s;print lines "\t"}' | awk '!max{max=$1}{s=$1/max*100;c=$1;$1="";printf "%-10s \t %10d \t %7.2f%%\n",$0,c,s;}' > DC_counts_and_percentages.tsv
awk -F"\t" '{print $14}' PHL.tsv | sed -r 's/.[(].*//g' | sort | uniq -c | awk '{s+=$1;lines=lines"\n"$0} END {printf "%d Total",s;print lines "\t"}' | awk '!max{max=$1}{s=$1/max*100;c=$1;$1="";printf "%-10s \t %10d \t %7.2f%%\n",$0,c,s;}' > PHL_counts_and_percentages.tsv






